import { ArchivePreview } from "./archive-elements";
import { About, Footer, Schedule } from "./nightly";

export const japanNote = "我们家三毛十一岁啦";

export function JapanHome({ archived = false }: { archived?: boolean }) {
  return <main className="japan-page">
    <section className="japan-cover" id="tonight" aria-labelledby="song-title">
      <nav className="japan-nav"><a href="/">FriendsFM!</a><div><a href={archived ? "/#about" : "#about"}>How it works</a><a href="/archive">Archive ↗</a></div></nav>
      <div className="japan-dateline"><span>October 11, 2026</span><span>No. 038 · Sent by TT</span></div>
      <header className="japan-heading"><p>Tonight’s song</p><h1 id="song-title">Japan<span aria-hidden="true">.</span></h1><div><span>Jan A.P. Kaczmarek</span><span>A small birthday dedication</span></div></header>
      <div className="japan-stage"><figure><img src="/japan-share.png" alt="Original AI-made soundtrack-inspired sleeve: a warmly lit piano and a small birthday card; not a film still" fetchPriority="high"/><figcaption>AN ORIGINAL SLEEVE · INSPIRED BY THE SOUNDTRACK</figcaption></figure><div className="japan-dedication"><span className="japan-overline">Eleven, and counting.</span><div className="japan-eleven" aria-hidden="true">11<span>years</span></div><blockquote><span>A note from TT</span><p lang="zh">{japanNote}</p></blockquote><a className="japan-listen" href="#story">Play this little dedication <span>↗</span></a></div></div>
      <div className="japan-strip"><span>Hachi: A Dog’s Tale</span><span>Original Motion Picture Soundtrack · Track 01</span><span>03:27</span></div>
    </section>
    <section className="japan-story" id="story"><header><p className="japan-overline">Listening notes · FriendsFM</p><h2>For the days<br/>we get to<br/><em>share.</em></h2><p>A film score.<br/>A birthday.<br/>A reason to press play.</p></header><div className="japan-story-body"><h3 lang="zh">把一起度过的日子，<br/>放进一首曲子里。</h3><div className="japan-prose" lang="zh"><p>《Japan》是 Jan A.P. Kaczmarek 为《忠犬八公的故事》（Hachi: A Dog’s Tale）创作的配乐，也是电影原声的第一轨。2009 年的电影从一场偶遇展开：Richard Gere 饰演的教授在回家途中发现一只走失的秋田犬，它慢慢成为家里的一员。关于相遇与陪伴的故事，就这样开始了。</p><p>今晚，TT 把这首曲子寄来，庆祝三毛十一岁。电影有电影的故事，这份推荐也有它自己的意义：不必借来一个宏大的理由，只是给一个重要的生日，留下一段音乐。</p></div><div className="embedded-player japan-player"><div className="player-label"><span>Jan A.P. Kaczmarek · Official audio</span><span>Track 01</span></div><div className="video-frame"><iframe title="Japan — Jan A.P. Kaczmarek, Hachi soundtrack" src="https://www.youtube.com/embed/YqfsBi3jIP4?playsinline=1&rel=0" width="100%" height="100%" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen referrerPolicy="strict-origin-when-cross-origin" loading="lazy"/></div><a href="https://www.youtube.com/watch?v=YqfsBi3jIP4" target="_blank" rel="noreferrer">Open on YouTube ↗</a><small>Artist Topic release, provided by The Orchard Enterprises. Playback availability may vary by region.</small></div><div className="japan-sources"><span>Sources & recording</span><a href="https://www.sonypictures.com/movies/hachiadogstale" target="_blank" rel="noreferrer">Sony Pictures · Film & synopsis ↗</a><a href="https://music.amazon.in/tracks/B095Z6M46J" target="_blank" rel="noreferrer">Amazon Music · Track listing & duration ↗</a><a href="https://www.youtube.com/watch?v=YqfsBi3jIP4" target="_blank" rel="noreferrer">Jan A.P. Kaczmarek · Official audio ↗</a><small>Listening notes by FriendsFM; TT’s words are preserved exactly. Original AI-generated artwork, inspired by the soundtrack’s warm cinematic palette. It is not a film still or a portrait of 三毛.</small></div></div></section>
    {archived ? <footer className="japan-footer"><span className="footer-brand">FriendsFM!</span><p>Postcard No. 038 · October 11, 2026</p><a href="/">Go to tonight →</a></footer> : <><Schedule entries={[]} theme="japan-shared"/><ArchivePreview current="japan"/><About theme="japan-shared"/><Footer/></>}
  </main>;
}
