import { ArchivePreview } from "./archive-elements";

type ScheduleEntry = { date: string; day: string; sender: string };

function Schedule({ entries, theme }: { entries: ScheduleEntry[]; theme: string }) {
  return (
    <section className={`schedule-board ${theme}`} aria-labelledby="queue-title">
      <div className="schedule-copy"><p className="section-kicker">Waiting to send</p><h2 id="queue-title">On the<br />way.</h2><p>The next postcards are already spoken for.</p></div>
      <ol className="schedule-list">
        {entries.map((entry) => <li key={entry.date}><span>{entry.day}</span><strong>{entry.sender}</strong><small>{entry.date}</small></li>)}
        <li className="schedule-open"><span>Next</span><strong>Open</strong><small>Send one in</small></li>
      </ol>
      <a className="schedule-cta" href="https://forms.gle/KH685ZJcGp6xmbKaA" target="_blank" rel="noreferrer">Take a night <span>↗</span></a>
    </section>
  );
}

function About({ theme }: { theme: string }) {
  return (
    <section className={`about ${theme}`} id="about" aria-labelledby="about-title">
      <div className="about-intro"><p className="section-kicker">FriendsFM · The idea</p><h2 id="about-title">What is this?</h2><p className="about-statement">Hi, this is David. I never know what to listen to, so I made this small website to ask my friends.</p><p className="about-motivation">I want to know what you’ve been listening to lately. FriendsFM is a way for us to pass songs around, find something new to hear, and keep in touch without needing a big reason to talk.</p></div>
      <div className="about-process" aria-labelledby="process-title"><p className="section-kicker" id="process-title">Here’s how it works</p><ol><li><span>01</span><div><h3>Send me a song.</h3><p>Add the track and your name. If you feel like it, write one short sentence about why you chose it. The note is totally optional.</p></div></li><li><span>02</span><div><h3>AI makes the night.</h3><p>When your turn comes up, AI finds the story behind the song and turns it into a recommendation: a listening page, a little context, and a one-off design made around the music.</p></div></li><li><span>03</span><div><h3>We keep the year.</h3><p>Every page stays in the archive. By the end of the year, we’ll have a strange, personal collection of songs from different friends, each with a really cool design to go with it (although AI-generated lol).</p></div></li></ol></div>
      <div className="about-invite" id="send-a-song"><p>The pages are generated. The recommendations aren’t.</p><h3>What should<br />we hear next?</h3><a href="https://forms.gle/KH685ZJcGp6xmbKaA" target="_blank" rel="noreferrer" className="about-cta">Send me a song <span>↗</span></a></div>
    </section>
  );
}

function Footer() { return <footer><span className="footer-brand">FriendsFM!</span><p>One night · One friend · One song</p><a href="#tonight">Back to tonight ↑</a></footer>; }

export function MovingHome() {
  return (
    <main className="moving-page">
      <section className="moving-cover" id="tonight" aria-labelledby="song-title"><img className="moving-cover-art" src="/moving-album-cover.jpg" alt="Album artwork for Moving by A-Yue Chang" /><div className="moving-overlay" /><a className="brand moving-brand" href="#tonight" aria-label="FriendsFM home">FriendsFM!</a><a className="how-link" href="#about">How it works <span>↓</span></a><a className="archive-link moving-archive-link" href="#archive">Archive <span>↘</span></a><div className="moving-date"><span>Aug 30, 2026</span><span>Postcard No. 002</span><span>Sent by David</span></div><div className="moving-title-block"><p className="tonight">Tonight’s song · No. 002</p><h1 id="song-title">搬家</h1><p className="moving-english-title">Sadly Moving On</p><div className="moving-meta"><p>张震岳<br /><span>Ayal Komod</span></p><p>跟着感觉走<br /><span>Rock Records · 2025</span></p></div></div><div className="moving-quote-card"><p>“老早以前以前听的，没多喜欢，最近搬家听到，感觉被一年前的子弹正中眉心。”</p><span>— David, tonight</span></div><a className="moving-enter" href="#story"><span className="moving-play">▶</span><span><strong>Enter tonight’s song</strong><small>4 min 01 sec · Track 02</small></span></a><div className="moving-scroll">Scroll to unpack <span>↓</span></div></section>
      <section className="moving-story" id="story" aria-labelledby="story-title"><div className="packing-tape tape-one" aria-hidden="true">FRAGILE · MEMORY · FRAGILE · MEMORY ·</div><div className="packing-tape tape-two" aria-hidden="true">THIS SIDE UP · THIS SIDE UP · THIS SIDE UP ·</div><div className="moving-story-heading"><p className="section-kicker">Why this one, tonight</p><h2 id="story-title">The boxes leave.<br />The past<br />doesn’t.</h2></div><div className="moving-story-body"><p className="moving-lede">搬家不难。难的是决定什么要带走，什么该留下。</p><div className="moving-copy"><p>相隔十二年，张震岳在 2025 年带着《跟着感觉走》回来，把这些年真实而普通的生活收进十首歌里。《搬家》排在第二首：它从收拾旧物开始，让照片、房间和一段关系的残影，一件一件重新出现。</p><p>滚石后来把它的影像称作《浪人的…》的续集——从辽阔海边回到逼仄城市，从浪漫的等待走进空掉的房间。旋律听起来平静、松弛，真正刺人的却是那件最日常的事：东西可以装箱，人的问题和回忆不会自动被搬走。</p></div><div className="embedded-player moving-player"><div className="player-label"><span>Listen here · No login</span><span>张震岳 · 搬家 · 4:01</span></div><div className="video-frame"><iframe title="YouTube player for 搬家 by 张震岳" src="https://www.youtube.com/embed/tt_JXfBIiBM?playsinline=1&rel=0" width="100%" height="100%" frameBorder="0" allowFullScreen referrerPolicy="strict-origin-when-cross-origin" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" loading="lazy" /></div></div><div className="sources moving-sources"><span>Listening notes assembled from</span><a href="https://dashi.streetvoice.cn/article/20250723/001/" target="_blank" rel="noreferrer">StreetVoice</a><a href="https://music.apple.com/cn/song/1827445751" target="_blank" rel="noreferrer">Apple Music</a><a href="https://www.youtube.com/watch?v=tt_JXfBIiBM" target="_blank" rel="noreferrer">Rock Records</a></div></div></section>
      <Schedule entries={[{ day: "Tomorrow", sender: "TT", date: "Aug 31" }, { day: "After", sender: "David", date: "Sep 01" }]} theme="moving-schedule" /><ArchivePreview current="moving" /><About theme="moving-about" /><Footer />
    </main>
  );
}

export function DearHome({ archived = false }: { archived?: boolean }) {
  return (
    <main className="dear-page">
      <section className="dear-cover" id="tonight" aria-labelledby="song-title"><div className="dear-wash" aria-hidden="true" /><img className="dear-cover-art" src="/dear-album-cover.jpg" alt="Official album artwork for 親愛的…我還不知道 by 張懸" /><div className="dear-rule" aria-hidden="true" /><a className="brand dear-brand" href={archived ? "/" : "#tonight"} aria-label={archived ? "Back to FriendsFM tonight" : "FriendsFM home"}>FriendsFM!</a>{!archived && <a className="how-link dear-how" href="#about">How it works <span>↓</span></a>}<a className="archive-link dear-archive-link" href={archived ? "/#archive" : "#archive"}>Archive <span>{archived ? "↖" : "↘"}</span></a><div className="dear-date"><span>Aug 31, 2026</span><span>Postcard No. 003</span><span>Sent by TT</span></div><div className="dear-title-block"><p className="tonight">{archived ? "From the archive" : "Tonight’s song"} · No. 003</p><h1 id="song-title">親愛的</h1><p className="dear-roman">Qin Ai De</p><div className="dear-meta"><p>張懸<br /><span>Deserts Xuan</span></p><p>親愛的…我還不知道<br /><span>Sony Music · 2007</span></p></div></div><div className="dear-note"><p>率真地感受世界，傻傻地去爱。<br /><strong>“别忘了温柔，别忘了快乐。”</strong></p><span>— TT, {archived ? "that night" : "tonight"}</span></div><a className="dear-enter" href="#story"><span>▶</span><div><strong>Enter {archived ? "this" : "tonight’s"} song</strong><small>4 min 15 sec · Track 04</small></div></a><div className="dear-scroll">Say it gently <span>↓</span></div></section>
      <section className="dear-story" id="story" aria-labelledby="story-title"><div className="dear-story-heading"><p className="section-kicker">Why this one, {archived ? "that night" : "tonight"}</p><h2 id="story-title">Say the deep<br />thing<br />gently.</h2></div><div className="dear-story-body"><p className="dear-lede">有些话不是因为不够深，才说得轻；而是因为太深，只能慢慢放下。</p><div className="dear-copy"><p>《親愛的》收在張懸 2007 年的第二張專輯《親愛的…我還不知道》，排在第四首。那張唱片花了半年製作；Sony 的介紹寫到，她包辦全數創作與編曲並參與製作，也堅持讓樂器以 live recording 留下各自的表情。</p><p>這首歌聽起來像把一封很長的信，折成幾個最簡單的提醒。它不替生活下結論，只把愛、受傷、放手與快樂放回日常語氣裡。TT 選出的那句話也正好抓住了它的尺度：溫柔不是輕描淡寫，而是一種仍願意好好感受的勇氣。</p></div><div className="embedded-player dear-player"><div className="player-label"><span>Listen here · No login</span><span>張懸 · 親愛的 · 4:15</span></div><div className="video-frame"><iframe title="YouTube player for 親愛的 by 張懸" src="https://www.youtube.com/embed/hhNBrmx69G8?playsinline=1&rel=0" width="100%" height="100%" frameBorder="0" allowFullScreen referrerPolicy="strict-origin-when-cross-origin" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" loading="lazy" /></div></div><div className="sources dear-sources"><span>Listening notes assembled from</span><a href="https://www.sonymusic.com.tw/album/%E8%A6%AA%E6%84%9B%E7%9A%84%E6%88%91%E9%82%84%E4%B8%8D%E7%9F%A5%E9%81%93-%E5%BC%B5%E6%87%B8-deserts-xuan-88697132622/" target="_blank" rel="noreferrer">Sony Music Taiwan</a><a href="https://open.spotify.com/album/7igO6sx0vVHEzo0xuDmRZA" target="_blank" rel="noreferrer">Spotify</a><a href="https://www.youtube.com/watch?v=hhNBrmx69G8" target="_blank" rel="noreferrer">YouTube Music</a></div></div></section>
      {archived ? <footer><span className="footer-brand">FriendsFM!</span><p>Postcard No. 003 · Aug 31, 2026</p><a href="/">Go to tonight →</a></footer> : <><Schedule entries={[{ day: "Tomorrow", sender: "David", date: "Sep 01" }]} theme="dear-schedule" /><ArchivePreview current="dear" /><About theme="dear-about" /><Footer /></>}
    </main>
  );
}

export function SchumannHome({ archived = false }: { archived?: boolean }) {
  return (
    <main className="schumann-page"><section className="schumann-cover" id="tonight" aria-labelledby="song-title"><img className="schumann-art" src="/schumann-sunset-postcard.png" alt="AI-generated print artwork of a sunset dissolving into a dark ocean" /><div className="schumann-shade" /><a className="brand schumann-brand" href={archived ? "/" : "#tonight"} aria-label={archived ? "Back to FriendsFM tonight" : "FriendsFM home"}>FriendsFM!</a>{!archived && <a className="how-link schumann-how" href="#about">How it works <span>↓</span></a>}<a className="archive-link schumann-archive-link" href={archived ? "/#archive" : "#archive"}>Archive <span>{archived ? "↖" : "↘"}</span></a><div className="schumann-date"><span>Sep 4, 2026</span><span>Postcard No. 007</span><span>Sent by David</span></div><div className="schumann-title-block"><p className="tonight">{archived ? "From the archive" : "Tonight’s song"} · No. 007</p><h1 id="song-title">Andante<br />cantabile</h1><div className="schumann-meta"><p>Robert Schumann<br /><span>Piano Quartet in E-flat major, Op. 47 · III</span></p><p>Ax · Stern · Laredo · Ma<br /><span>Sony Classical · 1994</span></p></div></div><div className="schumann-note"><p>“For some reason, this song always makes me think of sunset and ocean.”</p><span>— David, {archived ? "that night" : "tonight"}</span></div><a className="schumann-enter" href="#story"><span className="schumann-play">▶</span><span><strong>Enter {archived ? "this" : "tonight’s"} song</strong><small>7 min 04 sec · four players</small></span></a><div className="schumann-scroll">Follow the last light <span>↓</span></div></section>
      <section className="schumann-story" id="story" aria-labelledby="story-title"><div className="horizon-lines" aria-hidden="true">{Array.from({ length: 8 }).map((_, index) => <i key={index} />)}</div><div className="schumann-story-heading"><p className="section-kicker">Why this one, tonight</p><h2 id="story-title">Where the light<br />keeps<br />singing.</h2></div><div className="schumann-story-body"><p className="schumann-lede">The cello begins like a line of light on water: warm, unhurried, and already on its way somewhere else.</p><div className="schumann-copy"><p>Schumann wrote the E-flat Piano Quartet in 1842, the year he turned intensely toward chamber music. Its third movement is marked <em>Andante cantabile</em>—at a walking pace, and singing. In this 1994 Sony recording, Yo-Yo Ma’s opening cello line seems to stretch the horizon while Emanuel Ax, Isaac Stern, and Jaime Laredo slowly widen the color around it.</p><p>The music never needs to paint a literal sea. It moves the way dusk does: one long melody passing through changing light, becoming fuller, briefly shadowed, then returning with a different weight. Near the close, Schumann even asks the cellist to lower the bottom string for the final bars. The sound settles lower as the last glow disappears.</p></div><div className="embedded-player schumann-player"><div className="player-label"><span>Listen here · No login</span><span>Schumann · Op. 47, III · 7:04</span></div><div className="video-frame"><iframe title="YouTube player for Schumann Piano Quartet Op. 47 III Andante cantabile" src="https://www.youtube.com/embed/nJ6w_HYb4QM?playsinline=1&rel=0" width="100%" height="100%" frameBorder="0" allowFullScreen referrerPolicy="strict-origin-when-cross-origin" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" loading="lazy" /></div></div><div className="sources schumann-sources"><span>Listening notes assembled from</span><a href="https://emanuelax.com/1994/06/14/beethoven-schumann-piano-quartets/" target="_blank" rel="noreferrer">Emanuel Ax</a><a href="https://music.apple.com/us/album/beethoven-schumann-piano-quartets/518662793" target="_blank" rel="noreferrer">Apple Music</a><a href="https://imslp.org/wiki/Piano_Quartet%2C_Op.47_%28Schumann%2C_Robert%29" target="_blank" rel="noreferrer">IMSLP</a><a href="https://www.youtube.com/watch?v=nJ6w_HYb4QM" target="_blank" rel="noreferrer">Sony Classical</a></div></div></section>
      {archived ? <footer><span className="footer-brand">FriendsFM!</span><p>Postcard No. 007 · Sep 4, 2026</p><a href="/">Go to tonight →</a></footer> : <><Schedule entries={[{ day: "Tomorrow", sender: "Lucy", date: "Sep 05" }]} theme="schumann-schedule" /><ArchivePreview current="schumann" /><About theme="schumann-about" /><Footer /></>}</main>
  );
}

export function StillLonelyHome({ archived = false }: { archived?: boolean }) {
  return (
    <main className="lonely-page">
      <section className="lonely-cover" id="tonight" aria-labelledby="song-title">
        <div className="lonely-stripes" aria-hidden="true" />
        <img className="lonely-cover-art" src="/still-lonely-album-cover.jpg" alt="Official album artwork for 還是會寂寞 by 陳綺貞" />
        <div className="lonely-glow" aria-hidden="true" />
        <a className="brand lonely-brand" href={archived ? "/" : "#tonight"} aria-label={archived ? "Back to FriendsFM tonight" : "FriendsFM home"}>FriendsFM!</a>
        {!archived && <a className="how-link lonely-how" href="#about">How it works <span>↓</span></a>}
        <a className="archive-link lonely-archive-link" href={archived ? "/#archive" : "#archive"}>Archive <span>{archived ? "↖" : "↘"}</span></a>
        <div className="lonely-date"><span>Sep 1, 2026</span><span>Postcard No. 004</span><span>Sent by TT</span></div>
        <div className="lonely-title-block"><p className="tonight">{archived ? "From the archive" : "Tonight’s song"} · No. 004</p><h1 id="song-title">還是會<br /><em>寂寞</em></h1><p className="lonely-english">Still Lonely</p><div className="lonely-meta"><p>陳綺貞<br /><span>Cheer Chen</span></p><p>還是會寂寞<br /><span>Magic Stone · 2000</span></p></div></div>
        <div className="lonely-note"><span className="lonely-sticker">LIVE SOON!</span><p>“某人要去现场看陈绮贞了嘿嘿”</p><span>— TT, {archived ? "that night" : "tonight"}</span></div>
        <a className="lonely-enter" href="#story"><span>▶</span><div><strong>Enter {archived ? "this" : "tonight’s"} song</strong><small>4 min 32 sec · Track 03</small></div></a>
        <div className="lonely-scroll">Press play, wait for the show <span>↓</span></div>
      </section>
      <section className="lonely-story" id="story" aria-labelledby="story-title">
        <div className="lonely-story-heading"><p className="section-kicker">Why this one, {archived ? "that night" : "tonight"}</p><h2 id="story-title">Lonely,<br />but not<br /><em>alone.</em></h2></div>
        <div className="lonely-story-body"><p className="lonely-lede">一首叫《還是會寂寞》的歌，今晚却像一张去现场之前，忍不住先寄出的邀请函。</p><div className="lonely-copy"><p>《還是會寂寞》发行于 2000 年 4 月，是陈绮贞第二张创作专辑的同名曲。那时她刚把校园与街头演出的轻盈，带进更完整的乐队声音里；清楚、克制的唱法之下，情绪却始终保留着没被说完的空白。</p><p>这张专辑后来入选中华音乐人交流协会年度十大优良专辑，同名曲也同时入围第 12 届金曲奖最佳作曲人与最佳音乐录影带。二十六年后，TT 送来的理由倒没有一点寂寞：有人要去现场看陈绮贞了。嘿嘿。</p></div><div className="embedded-player lonely-player"><div className="player-label"><span>Listen here · No login</span><span>陳綺貞 · 還是會寂寞 · 4:32</span></div><div className="video-frame"><iframe title="YouTube player for 還是會寂寞 by 陳綺貞" src="https://www.youtube.com/embed/Rus_oG1Esc4?playsinline=1&rel=0" width="100%" height="100%" frameBorder="0" allowFullScreen referrerPolicy="strict-origin-when-cross-origin" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" loading="lazy" /></div></div><div className="sources lonely-sources"><span>Listening notes assembled from</span><a href="https://www.cheerego.com/dome_web/bio.php" target="_blank" rel="noreferrer">Cheerego</a><a href="https://music.apple.com/us/song/661575512" target="_blank" rel="noreferrer">Apple Music</a><a href="https://www.youtube.com/watch?v=Rus_oG1Esc4" target="_blank" rel="noreferrer">Rock Records</a></div></div>
      </section>
      {archived ? <footer><span className="footer-brand">FriendsFM!</span><p>Postcard No. 004 · Sep 1, 2026</p><a href="/">Go to tonight →</a></footer> : <><Schedule entries={[{ day: "Tomorrow", sender: "YSY", date: "Sep 02" }, { day: "After", sender: "TT", date: "Sep 03" }, { day: "Then", sender: "David", date: "Sep 04" }]} theme="lonely-schedule" /><ArchivePreview current="lonely" /><About theme="lonely-about" /><Footer /></>}
    </main>
  );
}

export function GingerHome({ archived = false }: { archived?: boolean }) {
  return <main className="ginger-page">
    <section className="ginger-cover" id="tonight" aria-labelledby="song-title"><div className="ginger-grid" aria-hidden="true" /><img className="ginger-art" src="/tomoo-ginger-cover.jpg" alt="Official Ginger single artwork featuring a ginger cat at a breakfast table" /><div className="ginger-wash" /><a className="brand ginger-brand" href={archived ? "/" : "#tonight"}>FriendsFM!</a>{!archived && <a className="how-link ginger-how" href="#about">How it works <span>↓</span></a>}<a className="archive-link ginger-archive-link" href={archived ? "/#archive" : "#archive"}>Archive <span>{archived ? "↖" : "↘"}</span></a><div className="ginger-date"><span>Sep 2, 2026</span><span>Postcard No. 005</span><span>Sent by YSY</span></div><div className="ginger-title-block"><p className="tonight">{archived ? "From the archive" : "Tonight’s song"} · No. 005</p><h1 id="song-title">Ginger</h1><div className="ginger-meta"><p>TOMOO<br /><span>Written · arranged · sung</span></p><p>Ginger — Single<br /><span>August 10, 2021</span></p></div></div><div className="ginger-note"><span>NEW FIND ★</span><p>“最近发现的宝藏歌手”</p><small>— YSY, {archived ? "that night" : "tonight"}</small></div><a className="ginger-enter" href="#story"><span>▶</span><div><strong>Enter {archived ? "this" : "tonight’s"} song</strong><small>3 min 22 sec · no login</small></div></a><div className="ginger-scroll">Follow the crumbs <span>↓</span></div></section>
    <section className="ginger-story" id="story" aria-labelledby="story-title"><div className="ginger-story-heading"><p className="section-kicker">Why this one, {archived ? "that night" : "tonight"}</p><h2 id="story-title">Stay a<br />little<br /><em>wild.</em></h2></div><div className="ginger-story-body"><p className="ginger-lede">像一只把早餐桌弄得乱七八糟的橘猫：先闯进来，再若无其事地把整间房点亮。</p><div className="ginger-copy"><p>《Ginger》是 TOMOO 在 2021 年推出的第四支单曲，也是许多人第一次记住她的作品。轻快的钢琴、贝斯和鼓几乎以最小编制同时向前跑；她后来回忆，这首歌让自己第一次找到那种可以不收着、伸展开来唱的声音。</p><p>歌里把一个不够圆滑、总会碰翻东西的人，比作无法被关进笼子的 ginger cat。它可爱，并不是因为规矩，而是因为仍然保留着一点野。YSY 说这是最近发现的宝藏歌手——这首歌听起来，也正像翻开抽屉时突然滚出来的一块亮黄色糖。</p></div><div className="embedded-player ginger-player"><div className="player-label"><span>Listen here · No login</span><span>TOMOO · Ginger · 3:22</span></div><div className="video-frame"><iframe title="YouTube player for Ginger by TOMOO" src="https://www.youtube.com/embed/z01gL_ahiOQ?playsinline=1&rel=0" width="100%" height="100%" frameBorder="0" allowFullScreen referrerPolicy="strict-origin-when-cross-origin" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" loading="lazy" /></div></div><div className="sources ginger-sources"><span>Listening notes assembled from</span><a href="https://music.apple.com/us/song/1579694076" target="_blank" rel="noreferrer">Apple Music</a><a href="https://natalie.mu/music/pp/tomoo04" target="_blank" rel="noreferrer">Music Natalie</a><a href="https://www.youtube.com/watch?v=z01gL_ahiOQ" target="_blank" rel="noreferrer">TOMOO Official</a></div></div></section>
    {archived ? <footer><span className="footer-brand">FriendsFM!</span><p>Postcard No. 005 · Sep 2, 2026</p><a href="/">Go to tonight →</a></footer> : <><Schedule entries={[{ day: "Tomorrow", sender: "TT", date: "Sep 03" }, { day: "After", sender: "David", date: "Sep 04" }]} theme="ginger-schedule" /><ArchivePreview current="ginger" /><About theme="ginger-about" /><Footer /></>}
  </main>;
}

export function LiangboHome({ archived = false }: { archived?: boolean }) {
  return <main className="liangbo-page">
    <section className="liangbo-cover" id="tonight" aria-labelledby="song-title">
      <img className="liangbo-art" src="/liangbo-in-the-dark-art.png" alt="AI-generated night-stage artwork with a lone guitarist beneath a circular light" />
      <div className="liangbo-shade" aria-hidden="true" /><div className="liangbo-orbits" aria-hidden="true"><i /><i /><i /></div>
      <a className="brand liangbo-brand" href={archived ? "/" : "#tonight"}>FriendsFM!</a>{!archived && <a className="how-link liangbo-how" href="#about">How it works <span>↓</span></a>}<a className="archive-link liangbo-archive-link" href={archived ? "/#archive" : "#archive"}>Archive <span>{archived ? "↖" : "↘"}</span></a>
      <div className="liangbo-date"><span>Sep 3, 2026</span><span>Postcard No. 006</span><span>Sent by TT</span></div>
      <div className="liangbo-title-block"><p className="tonight">{archived ? "From the archive" : "Tonight’s song"} · No. 006</p><h1 id="song-title"><span>黑夜</span><em>中</em></h1><div className="liangbo-meta"><p>梁博<br /><span>Bruce Liang</span></p><p>Live recording<br /><span>Written · composed · arranged by 梁博</span></p></div></div>
      <div className="liangbo-note"><span className="liangbo-ticket">SEE YOU LIVE</span><p>“某人要去看梁博了嘿嘿”</p><small>— TT, {archived ? "that night" : "tonight"}</small></div>
      <a className="liangbo-enter" href="#story"><span>▶</span><div><strong>Enter {archived ? "this" : "tonight’s"} song</strong><small>7 min 06 sec · live</small></div></a><div className="liangbo-scroll">Walk into the dark <span>↓</span></div>
    </section>
    <section className="liangbo-story" id="story" aria-labelledby="liangbo-story-title">
      <div className="liangbo-story-heading"><p className="section-kicker">Why this one, {archived ? "that night" : "tonight"}</p><h2 id="liangbo-story-title">The dark<br />has a<br /><em>pulse.</em></h2><div className="liangbo-index"><span>01</span><span>First heard live</span><span>2019</span></div></div>
      <div className="liangbo-story-body"><p className="liangbo-lede">黑夜在这首歌里不是终点。它更像一段很长的路：鼓点在脚下，吉他在远处，而身边刚好还有一个人。</p><div className="liangbo-copy"><p>《黑夜中》由梁博包揽词、曲与编曲，2019 年在《我是唱作人》第一季首次演唱。它没有急着用副歌把情绪推满，而是让贝斯、鼓和吉他一点点扩大空间；唱到后来，原本安静的夜像被整支乐队从内部点亮。</p><p>梁博的作品常常要在现场里才真正长出完整形状。这一版来自《昼夜本色 第二季》的现场录音：七分钟里，克制和爆发不是两件事，而是同一条路上的呼吸。所以 TT 那句“某人要去看梁博了嘿嘿”很适合放在这里——这不是听完以后才想去现场的歌，它本身就像一张已经撕下来的票根。</p></div><div className="liangbo-pullquote"><span>ONE NIGHT</span><p>不是等天亮。<br />是在黑夜中继续走。</p></div><div className="embedded-player liangbo-player"><div className="player-label"><span>Listen here · No login</span><span>梁博 · 黑夜中 · 7:06</span></div><div className="video-frame"><iframe title="YouTube player for 黑夜中 by 梁博" src="https://www.youtube.com/embed/yAseLFhKDxQ?playsinline=1&rel=0" width="100%" height="100%" frameBorder="0" allowFullScreen referrerPolicy="strict-origin-when-cross-origin" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" loading="lazy" /></div></div><div className="sources liangbo-sources"><span>Listening notes assembled from</span><a href="https://www.youtube.com/watch?v=yAseLFhKDxQ" target="_blank" rel="noreferrer">Forest Child Music</a><a href="https://www.qobuz.com/us-en/album/-/jjcz3wuiosmea" target="_blank" rel="noreferrer">Qobuz</a><a href="https://music.douban.com/subject/33430391/" target="_blank" rel="noreferrer">Song notes</a></div></div>
    </section>
    {archived ? <footer><span className="footer-brand">FriendsFM!</span><p>Postcard No. 006 · Sep 3, 2026</p><a href="/">Go to tonight →</a></footer> : <><Schedule entries={[{ day: "Tomorrow", sender: "David", date: "Sep 04" }]} theme="liangbo-schedule" /><ArchivePreview current="liangbo" /><About theme="liangbo-about" /><Footer /></>}
  </main>;
}

export function DijonHome({ archived = false }: { archived?: boolean }) {
  return (
    <main className="dijon-page">
      <section className="dijon-cover" id="tonight" aria-labelledby="song-title">
        <img className="dijon-art" src="/dijon-nicos-red-truck-cover.jpg" alt="Official single artwork for Nico's Red Truck by Dijon, showing a rider on horseback above a car and a man in the foreground" />
        <div className="dijon-shade" aria-hidden="true" />
        <div className="dijon-frame" aria-hidden="true" />
        <a className="brand dijon-brand" href={archived ? "/" : "#tonight"}>FriendsFM!</a>
        {!archived && <a className="how-link dijon-how" href="#about">How it works <span>↓</span></a>}
        <a className="archive-link dijon-archive-link" href={archived ? "/#archive" : "#archive"}>Archive <span>{archived ? "↖" : "↘"}</span></a>
        <div className="dijon-date"><span>Sep 5, 2026</span><span>Postcard No. 008</span><span>Sent by Lucy</span></div>
        <div className="dijon-title-block"><p className="tonight">{archived ? "From the archive" : "Tonight’s song"} · No. 008</p><h1 id="song-title">Nico’s<br /><em>Red Truck</em></h1><div className="dijon-meta"><p>Dijon<br /><span>Written · produced by Dijon</span></p><p>Nico’s Red Truck — Single<br /><span>Dark Green · 2018</span></p></div></div>
        <div className="dijon-note"><span>FROM THE ROAD</span><p>“有一天听着走在巴黎街头感觉很有感觉”</p><small>— Lucy, {archived ? "that night" : "tonight"}</small></div>
        <a className="dijon-enter" href="#story"><span>▶</span><div><strong>Enter {archived ? "this" : "tonight’s"} song</strong><small>4 min 08 sec · official video</small></div></a>
        <div className="dijon-scroll">Keep the snapshot <span>↓</span></div>
      </section>
      <section className="dijon-story" id="story" aria-labelledby="dijon-story-title">
        <div className="dijon-story-heading"><p className="section-kicker">Why this one, {archived ? "that night" : "tonight"}</p><h2 id="dijon-story-title">A memory<br />with the<br /><em>engine on.</em></h2><div className="dijon-stamp"><span>09 · 20 · 18</span><span>DARK GREEN</span></div></div>
        <div className="dijon-story-body"><p className="dijon-lede">有些歌像旧照片：颜色已经褪了，手一摸，还是会有一点温度。</p><div className="dijon-copy"><p>《Nico’s Red Truck》是 Dijon 在 2018 年发布的单曲，词、曲与制作都由他完成。歌一开始就把人放进一场移动的回忆：雨、道路、朋友、照片，还有那些当时普通得不值得记录的细节。</p><p>它的声音也保留着这种“不太整理过”的质感——像从车里望出去的画面，边缘有一点晃，远处却很亮。Lucy 说，某天走在巴黎街头听到它，突然觉得很有感觉；这正是它迷人的地方：它记住的不是宏大的过去，而是一个人边走边被某个瞬间击中的时候。</p></div><div className="dijon-pullquote"><span>ONE FRAME</span><p>Keep the picture moving.<br />Let the feeling catch up.</p></div><div className="embedded-player dijon-player"><div className="player-label"><span>Listen here · No login</span><span>Dijon · Nico’s Red Truck · 4:08</span></div><div className="video-frame"><iframe title="YouTube player for Nico's Red Truck by Dijon" src="https://www.youtube.com/embed/fA5QVGlTHa0?playsinline=1&rel=0" width="100%" height="100%" frameBorder="0" allowFullScreen referrerPolicy="strict-origin-when-cross-origin" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" loading="lazy" /></div></div><div className="sources dijon-sources"><span>Listening notes assembled from</span><a href="https://dijondijon.bandcamp.com/track/nicos-red-truck" target="_blank" rel="noreferrer">Dijon · Bandcamp</a><a href="https://www.youtube.com/watch?v=fA5QVGlTHa0" target="_blank" rel="noreferrer">Dijon · YouTube</a><a href="https://music.apple.com/us/song/1869353873" target="_blank" rel="noreferrer">Apple Music</a><a href="https://open.spotify.com/track/4zHC1zzSAV2xR7OlUqo2Oz" target="_blank" rel="noreferrer">Spotify</a></div></div>
      </section>
      {archived ? <footer><span className="footer-brand">FriendsFM!</span><p>Postcard No. 008 · Sep 5, 2026</p><a href={archived ? "/" : "#tonight"}>Go to tonight →</a></footer> : <><Schedule entries={[{ day: "Tomorrow", sender: "YSY", date: "Sep 06" }, { day: "After", sender: "David", date: "Sep 07" }]} theme="dijon-schedule" /><ArchivePreview current="dijon" /><About theme="dijon-about" /><Footer /></>}
    </main>
  );
}

export function MyLifeHome({ archived = false }: { archived?: boolean }) {
  return (
    <main className="my-life-page">
      <section className="my-life-cover" id="tonight" aria-labelledby="song-title">
        <div className="my-life-keys" aria-hidden="true">{Array.from({ length: 11 }).map((_, index) => <i key={index} />)}</div>
        <img className="my-life-art" src="/billy-joel-52nd-street-cover.jpg" alt="Official 52nd Street album artwork featuring Billy Joel on a New York street" />
        <div className="my-life-shade" aria-hidden="true" />
        <div className="my-life-frame" aria-hidden="true"><span>SHIFT 09 · 06</span><span>PLAY IT BACK</span></div>
        <a className="brand my-life-brand" href={archived ? "/" : "#tonight"}>FriendsFM!</a>
        {!archived && <a className="how-link my-life-how" href="#about">How it works <span>↓</span></a>}
        <a className="archive-link my-life-archive-link" href={archived ? "/#archive" : "#archive"}>Archive <span>{archived ? "↖" : "↘"}</span></a>
        <div className="my-life-date"><span>Sep 6, 2026</span><span>Postcard No. 009</span><span>Sent by YSY</span></div>
        <div className="my-life-title-block"><p className="tonight">{archived ? "From the archive" : "Tonight’s song"} · No. 009</p><h1 id="song-title">My<br /><em>Life</em></h1><div className="my-life-meta"><p>Billy Joel<br /><span>Written · performed by Billy Joel</span></p><p>52nd Street<br /><span>Columbia · 1978</span></p></div></div>
        <div className="my-life-note"><span>CAUGHT ON SHIFT</span><p>“在 AutoZone 店里培训时，一下被钢琴的节奏抓住。”</p><small>— YSY, {archived ? "that night" : "tonight"}</small></div>
        <a className="my-life-enter" href="#story"><span>▶</span><div><strong>Enter {archived ? "this" : "tonight’s"} song</strong><small>4 min 45 sec · official audio</small></div></a>
        <div className="my-life-scroll">Clock out, turn it up <span>↓</span></div>
      </section>
      <section className="my-life-story" id="story" aria-labelledby="my-life-story-title">
        <div className="my-life-story-heading"><p className="section-kicker">Why this one, {archived ? "that night" : "tonight"}</p><h2 id="my-life-story-title">The keys<br />cut<br /><em>through.</em></h2><div className="my-life-punch"><span>52</span><small>ND STREET<br />NEW YORK · 1978</small></div></div>
        <div className="my-life-story-body"><p className="my-life-lede">有时候一首歌不是被找来的。它只是在最不浪漫的地方，忽然把你拦住。</p><div className="my-life-copy"><p>《My Life》收在 Billy Joel 1978 年的专辑《52nd Street》，排在第三首。专辑由 Phil Ramone 制作，也让 Billy Joel 第一次拿到格莱美年度专辑奖；这首歌随后成为一支 Top 5 单曲。</p><p>近五十年以后，它却不是在唱片店或深夜酒吧里重新出现，而是在一次 AutoZone 店内培训中，被钢琴节奏硬生生从背景里拉到眼前。环境越普通，那一下越准确：你还在上班，歌已经替你把门推开了。</p></div><div className="my-life-pullquote"><span>TRAINING NOTE · 05:22 PM</span><p>Some songs wait for the right room.<br />This one made its own.</p></div><div className="embedded-player my-life-player"><div className="player-label"><span>Listen here · No login</span><span>Billy Joel · My Life · 4:45</span></div><div className="video-frame"><iframe title="YouTube player for My Life by Billy Joel" src="https://www.youtube.com/embed/HVX80UpMPDI?playsinline=1&rel=0" width="100%" height="100%" frameBorder="0" allowFullScreen referrerPolicy="strict-origin-when-cross-origin" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" loading="lazy" /></div></div><div className="sources my-life-sources"><span>Listening notes assembled from</span><a href="https://www.billyjoel.com/music/52nd-street/" target="_blank" rel="noreferrer">Billy Joel</a><a href="https://music.apple.com/us/album/52nd-street/259573387" target="_blank" rel="noreferrer">Apple Music</a><a href="https://www.youtube.com/watch?v=HVX80UpMPDI" target="_blank" rel="noreferrer">Official audio</a></div></div>
      </section>
      {archived ? <footer><span className="footer-brand">FriendsFM!</span><p>Postcard No. 009 · Sep 6, 2026</p><a href="/">Go to tonight →</a></footer> : <><Schedule entries={[{ day: "Tomorrow", sender: "David", date: "Sep 07" }]} theme="my-life-schedule" /><ArchivePreview current="my-life" /><About theme="my-life-about" /><Footer /></>}
    </main>
  );
}

export function GuoYuanChaoHome({ archived = false }: { archived?: boolean }) {
  return (
    <main className="guo-page">
      <section className="guo-cover" id="tonight" aria-labelledby="song-title">
        <img className="guo-art" src="/song-dongye-guo-yuan-chao-cover.jpg" alt="Official monochrome artwork for 郭源潮 by 宋冬野, with figures beneath layered clouds" />
        <div className="guo-shade" aria-hidden="true" /><div className="guo-cloud-lines" aria-hidden="true"><i /><i /><i /></div>
        <a className="brand guo-brand" href={archived ? "/" : "#tonight"}>FriendsFM!</a>
        {!archived && <a className="how-link guo-how" href="#about">How it works <span>↓</span></a>}
        <a className="archive-link guo-archive-link" href={archived ? "/#archive" : "#archive"}>Archive <span>{archived ? "↖" : "↘"}</span></a>
        <div className="guo-date"><span>Sep 7, 2026</span><span>Postcard No. 010</span><span>Sent by David</span></div>
        <div className="guo-title-block"><p className="tonight">{archived ? "From the archive" : "Tonight’s song"} · No. 010</p><h1 id="song-title"><span>郭</span><span>源</span><span>潮</span></h1><div className="guo-meta"><p>宋冬野<br /><span>Song Dongye</span></p><p>再想想 · Track 09<br /><span>Modern Sky · 2026</span></p></div></div>
        <div className="guo-note"><span>ANOTHER MOMENT</span><p>“宋冬野最近出新专了”</p><small>— David, {archived ? "that night" : "tonight"}</small></div>
        <a className="guo-enter" href="#story"><span>▶</span><div><strong>Enter {archived ? "this" : "tonight’s"} song</strong><small>7 min 22 sec · official video</small></div></a>
        <div className="guo-scroll">Go back through the clouds <span>↓</span></div>
      </section>
      <section className="guo-story" id="story" aria-labelledby="guo-story-title">
        <div className="guo-story-heading"><p className="section-kicker">Why this one, {archived ? "that night" : "tonight"}</p><h2 id="guo-story-title">听过以后，<br />再<br /><em>想想。</em></h2><div className="guo-years"><span>2017</span><i /><span>2026</span></div></div>
        <div className="guo-story-body"><p className="guo-lede">一首歌走了九年，再回到同一张唱片里，已经不可能只是原来的那首歌。</p><div className="guo-copy"><p>《郭源潮》最早在 2017 年作为单曲发行。它让宋冬野从早期的城市民谣，走向更完整、更有起伏的乐队编配；第二年，这首作品为他拿下第 29 届金曲奖最佳作词人。</p><p>2026 年，宋冬野把它重新收进第二张个人原创专辑《再想想》：一张与《安和桥北》相隔十三年的唱片。《郭源潮》排在第九首，和《空港曲》《知道》一起被放回新的十一首曲序里。David 说“最近出新专了”——今晚刚好不必急着追新，只需要听一首旧歌如何被时间重新排列。</p></div><div className="guo-pullquote"><span>NINE YEARS LATER</span><p>不是回到从前。<br />是让从前再经过一次。</p></div><div className="embedded-player guo-player"><div className="player-label"><span>Listen here · No login</span><span>宋冬野 · 郭源潮 · 7:22</span></div><div className="video-frame"><iframe title="YouTube player for 郭源潮 by 宋冬野" src="https://www.youtube.com/embed/0IWVfD535yw?playsinline=1&rel=0" width="100%" height="100%" frameBorder="0" allowFullScreen referrerPolicy="strict-origin-when-cross-origin" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" loading="lazy" /></div></div><div className="sources guo-sources"><span>Listening notes assembled from</span><a href="https://www.youtube.com/watch?v=0IWVfD535yw" target="_blank" rel="noreferrer">宋冬野 · Official MV</a><a href="https://www.modernsky.com/home/artists/42" target="_blank" rel="noreferrer">Modern Sky</a><a href="https://open.spotify.com/embed/album/10ybjitbVIXwzgwfW7HLRc" target="_blank" rel="noreferrer">再想想 · Album</a></div></div>
      </section>
      {archived ? <footer><span className="footer-brand">FriendsFM!</span><p>Postcard No. 010 · Sep 7, 2026</p><a href="/">Go to tonight →</a></footer> : <><Schedule entries={[]} theme="guo-schedule" /><ArchivePreview current="guo-yuan-chao" /><About theme="guo-about" /><Footer /></>}
    </main>
  );
}

export function BozHome({ archived = false }: { archived?: boolean }) {
  return (
    <main className="boz-page">
      <section className="boz-cover" id="tonight" aria-labelledby="song-title">
        <img className="boz-art" src="/boz-scaggs-down-two-then-left-cover.webp" alt="Official album artwork for Down Two Then Left by Boz Scaggs, featuring the singer walking beside ice sculptures" />
        <div className="boz-stripes" aria-hidden="true" />
        <div className="boz-shade" aria-hidden="true" />
        <div className="boz-ice-ring" aria-hidden="true" />
        <a className="brand boz-brand" href={archived ? "/" : "#tonight"}>FriendsFM!</a>
        {!archived && <a className="how-link boz-how" href="#about">How it works <span>↓</span></a>}
        <a className="archive-link boz-archive-link" href={archived ? "/#archive" : "#archive"}>Archive <span>{archived ? "↖" : "↘"}</span></a>
        <div className="boz-date"><span>Sep 6, 2026</span><span>Postcard No. 009</span><span>Sent by Joey</span></div>
        <div className="boz-title-block"><p className="tonight">{archived ? "From the archive" : "Tonight’s song"} · No. 009</p><h1 id="song-title">Still<br /><em>Falling</em><br />For You</h1><div className="boz-meta"><p>Boz Scaggs<br /><span>Written by B. Scaggs</span></p><p>Down Two Then Left<br /><span>Columbia · 1977</span></p></div></div>
        <div className="boz-note"><span>COOL SIDE / WARM HEART</span><p>A song for the part of the night that still has somewhere to go.</p><small>— Joey, {archived ? "that night" : "tonight"}</small></div>
        <a className="boz-enter" href="#story"><span>▶</span><div><strong>Enter {archived ? "this" : "tonight’s"} song</strong><small>3 min 53 sec · official audio</small></div></a>
        <div className="boz-scroll">Walk past the ice <span>↓</span></div>
      </section>
      <section className="boz-story" id="story" aria-labelledby="boz-story-title">
        <div className="boz-story-heading"><p className="section-kicker">Why this one, {archived ? "that night" : "tonight"}</p><h2 id="boz-story-title">Stay<br />a little<br /><em>longer.</em></h2><div className="boz-index"><span>09</span><span>Down Two Then Left</span><span>1977</span></div></div>
        <div className="boz-story-body"><p className="boz-lede">有些歌表面上很冷，真正靠近以后，里面一直有温度。</p><div className="boz-copy"><p>《Still Falling for You》收在 Boz Scaggs 1977 年的专辑《Down Two Then Left》中。它只有三分五十三秒，却把一种很难解释的状态唱得很完整：人已经往前走了，心里还保留着一点没有关上的门。</p><p>这张唱片的封面让 Boz 走在一排冰雕旁边，画面冷静、干净，几乎没有多余动作。歌却不是一块冰。贝斯、鼓和吉他把节奏稳稳地推着往前，声音里有夜色的光泽，也有一种不急着证明什么的坚持。</p></div><div className="boz-pullquote"><span>ONE MORE TURN</span><p>The night is cool.<br />The feeling isn’t.</p></div><div className="embedded-player boz-player"><div className="player-label"><span>Listen here · No login</span><span>Boz Scaggs · Still Falling for You · 3:53</span></div><div className="video-frame"><iframe title="YouTube player for Still Falling for You by Boz Scaggs" src="https://www.youtube.com/embed/NCQjhhmw1WA?playsinline=1&rel=0" width="100%" height="100%" frameBorder="0" allowFullScreen referrerPolicy="strict-origin-when-cross-origin" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" loading="lazy" /></div></div><div className="sources boz-sources"><span>Listening notes assembled from</span><a href="https://www.bozscaggs.com/discography" target="_blank" rel="noreferrer">Boz Scaggs · Discography</a><a href="https://music.apple.com/us/song/188251640" target="_blank" rel="noreferrer">Apple Music</a><a href="https://www.youtube.com/watch?v=NCQjhhmw1WA" target="_blank" rel="noreferrer">Boz Scaggs · YouTube</a><a href="https://open.spotify.com/track/3QDcy2wlMzSHqoQpMaZyJI" target="_blank" rel="noreferrer">Spotify</a></div></div>
      </section>
      {archived ? <footer><span className="footer-brand">FriendsFM!</span><p>Postcard No. 009 · Sep 6, 2026</p><a href="/">Go to tonight →</a></footer> : <><Schedule entries={[]} theme="boz-schedule" /><ArchivePreview current="still-falling-for-you" /><About theme="boz-about" /><Footer /></>}
    </main>
  );
}
